
export const CUSTOM_GUITAR_CREATE_REQUEST = 'CUSTOM_GUITAR_CREATE_REQUEST'
export const CUSTOM_GUITAR_CREATE_SUCCESS = 'CUSTOM_GUITAR_CREATE_SUCCESS'
export const CUSTOM_GUITAR_CREATE_FAIL = 'CUSTOM_GUITAR_CREATE_FAIL'
export const CUSTOM_GUITAR_CREATE_RESET = 'CUSTOM_GUITAR_CREATE_RESET'
