export const GUITAR_LIST_REQUEST = 'GUITAR_LIST_REQUEST'
export const GUITAR_LIST_SUCCESS = 'GUITAR_LIST_SUCCESS'
export const GUITAR_LIST_FAIL = 'GUITAR_LIST_FAIL'

export const GUITAR_DETAILS_REQUEST = 'GUITAR_DETAILS_REQUEST'
export const GUITAR_DETAILS_SUCCESS = 'GUITAR_DETAILS_SUCCESS'
export const GUITAR_DETAILS_FAIL = 'GUITAR_DETAILS_FAIL'

export const GUITAR_CREATE_REVIEW_REQUEST = 'GUITAR_CREATE_REVIEW_REQUEST'
export const GUITAR_CREATE_REVIEW_SUCCESS = 'GUITAR_CREATE_REVIEW_SUCCESS'
export const GUITAR_CREATE_REVIEW_FAIL = 'GUITAR_CREATE_REVIEW_FAIL'
export const GUITAR_CREATE_REVIEW_RESET = 'GUITAR_CREATE_REVIEW_RESET'

export const GUITAR_TOP_REQUEST = 'GUITAR_TOP_REQUEST'
export const GUITAR_TOP_SUCCESS = 'GUITAR_TOP_SUCCESS'
export const GUITAR_TOP_FAIL = 'GUITAR_TOP_FAIL'