# Generated by Django 4.2.6 on 2023-10-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20231010_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGuitar',
            fields=[
                ('numOfStrings', models.CharField(blank=True, max_length=200, null=True)),
                ('rlHanded', models.CharField(blank=True, max_length=200, null=True)),
                ('scaleLength', models.CharField(blank=True, max_length=200, null=True)),
                ('construction', models.CharField(blank=True, max_length=200, null=True)),
                ('bodyShape', models.CharField(blank=True, max_length=200, null=True)),
                ('bodyMaterial', models.CharField(blank=True, max_length=200, null=True)),
                ('topWoodOptions', models.CharField(blank=True, max_length=200, null=True)),
                ('bodyBinding', models.CharField(blank=True, max_length=200, null=True)),
                ('bindingMaterial', models.CharField(blank=True, max_length=200, null=True)),
                ('finish', models.CharField(blank=True, max_length=200, null=True)),
                ('headstockShape', models.CharField(blank=True, max_length=200, null=True)),
                ('headstock', models.CharField(blank=True, max_length=200, null=True)),
                ('headstockFinish', models.CharField(blank=True, max_length=200, null=True)),
                ('headstockBinding', models.CharField(blank=True, max_length=200, null=True)),
                ('trussRodCover', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('neckMaterial', models.CharField(blank=True, max_length=200, null=True)),
                ('neckShape', models.CharField(blank=True, max_length=200, null=True)),
                ('nutWidth6', models.CharField(blank=True, max_length=200, null=True)),
                ('nutWidth7', models.CharField(blank=True, max_length=200, null=True)),
                ('nutWidth8', models.CharField(blank=True, max_length=200, null=True)),
                ('thicknessAt1stand12thFret', models.CharField(blank=True, max_length=200, null=True)),
                ('neckFinish', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
